### ISSUE TITLE
Add Internal Documentation to Wiki

### ISSUE THREAD

**Issue by pacholoamit** [MediaJel/mediajel-tracker#178]
### Description

Add internal documentation to Wiki: https://github.com/MediaJel/mediajel-tracker/wiki

**Comment by HansMediaJel** [comment]
The documents are done, please use the links below.

Mediajel Onboarding Documentation HTML :
https://docs.google.com/document/d/1VAAjSJw618fq1BY7t7hJTcncItIDi2TF/edit?usp=share_link&ouid=115685225735130004052&rtpof=true&sd=true

Woocommerce Tag Integration Client version 1.2 :
https://docs.google.com/document/d/1XJYXzrK-ohH-AP8ecTm2fHxx5k-TwzGH/edit?usp=share_link&ouid=115685225735130004052&rtpof=true&sd=true

Shopify Tag Integration Client version 1.2 :
https://docs.google.com/document/d/1a7_odcZldI_vUHzY7HHHtRHH-lL-QntB/edit?usp=share_link&ouid=115685225735130004052&rtpof=true&sd=true

GTM Tag Integration Client :
https://docs.google.com/document/d/1RHDxFnpwVRaYn--XQOlG-RkKACbs0pPB/edit?usp=share_link&ouid=115685225735130004052&rtpof=true&sd=true

**Comment by HansMediaJel** [comment]
**These versions are for internal developers only.**

Shopify Tag Integration Developer version 1.1
https://docs.google.com/document/d/1iEX9KBEErTYDXsqf-667yiGDWhx8S6Em/edit?usp=sharing&ouid=115685225735130004052&rtpof=true&sd=true

Woocommerce Tag Integration Developer ver1.1
https://docs.google.com/document/d/1isXN6tI0JtPtPfUuDAkPJCqr0p0PtBq0/edit?usp=sharing&ouid=115685225735130004052&rtpof=true&sd=true
