### ISSUE TITLE
New ecomm platform "Weave" - integration assessment

### ISSUE THREAD

**Issue by rmm03** [MediaJel/mediajel-tracker#193]
Title of Request:
New ecomm platform "Weave" - integration assessment

Your Name:
Ben

Type of Request:
Task

Request:
Hey Pach, SM Services is asking if we're able to integrate with a new platform called Weave. Here's a site that's using it:

https://static.weaveiq.com/ordering/710/index.html?lid=ef5c&category=flower&subcategory=sativa#inventory

**Comment by pacholoamit** [comment]
Hello! This is completed. I've relayed the information to Ben Thank you!
