### ISSUE TITLE
Fixed shopify order id

### ISSUE THREAD

**Issue by kimoycatayas** [MediaJel/mediajel-tracker#234]
![Image](https://user-images.githubusercontent.com/47773040/238468890-80381ac2-379c-447a-b01e-8b262bd6f47e.png)

**Comment by kimoycatayas** [comment]
Previously, we were using the order id from the `window.Shopify.checkout` object which is a uid number. 
But now we are using the `order_number` from the DOM as per requested by client.

**Comment by pacholoamit** [comment]
Update: We'll make a change to include the `unique order number -- friendly order number`
