### ISSUE TITLE
Create documentation for Integrations Engineer onboarding in the mediajel-tracker wiki

### ISSUE THREAD

**Issue by pacholoamit** [MediaJel/mediajel-tracker#251]
# Description

Create onboarding documentation for integrations in markdown

```
1. Snowplow Javascript tags
1a. A brief overview of Snowplow tags
1b. Tools required (Snowplow chrome extension) for debugging
1c. Tracking transactions and signups

2. The Mediajel tracker
2a. How to use the mediajel tracker
2b. How to generate a mediajel tracker tag (Dashboard)
2c. How to check transactions (Kibana & Snowflake)

```

**Comment by ZeeLiger** [comment]
1. Snowplow Javascript tags
   1a. A brief overview of Snowplow tags
   1b. Tools required (Snowplow chrome extension) for debugging
Recommended things to do
   - New profile for browser
   - Add Extensions:
     - Tag Assistant Legacy (by Google)
     - UET Tag Helper (by Microsoft Advertising)
     - Snowplow Inspector
     - Hoxx VPN Proxy
  
   1c. Tracking transactions and signups

2. The Mediajel tracker
   2a. How to use the mediajel tracker
   2b. How to generate a mediajel tracker tag (Dashboard)
   For Testing
   - Go to Dojo
   - Then orgconfig
   - Click the Tracking Tab at the top
   - Click New Tracking Tag at the right side
   - Specify a name and a Cart
   - After creating the tag, it should show up on the tracking area with the other tags and click to open it
   - You can see "view instructions". Each set of Cart has different instructions. Follow them for installation
 
   2c. How to check transactions (Kibana & Snowflake)
   To check if the Tag is working (console):
   - Go to the website that has the Tag installed.
   - Open the console (right click > inspect > console)
   - Check here if there is a Tracker that is working
   - Another Check is to go to snowplow (same area as console > either on the far right or hidden in the ">>" button > snowplow)
   - There should be data being passed to snowplow

# Tag Installation Guide 101

1. Test for Tag Installation
   - IF there are needed info that can't be provided THEN can't test SUCH AS credit card (usually on websites such as shopify)
   - IF can provide THEN test SUCH AS email (use mdiajel email)
   - TRY to purchase AND Write on special instructions / order instructions TEST ORDER. DO NOT PROCESS
   - IF can test properly and enter the transaction THEN
2. Tag Installation
   - IF it is a supported Environment then use the mediajel tracker support, ELSE go to Custom Tag Installation
3. Custom Tag Installation
   - Test at Console
   - Trial and Error - get the values of the HTML to put in JavaScript
   - Check Snowplow if the info is being passed

# Definition of Terms

- Publishers = Sites and Apps and Domains
- Pixel = Tag (Pixel Installation = Tag Installation)
- KPI (Key Performance Indicator) = Transactions
- Environment / Cart = Website / Shop that is hosting the customer? (Shopify, Woocomerce)

**Comment by pacholoamit** [comment]
Link to wiki here: https://github.com/MediaJel/mediajel-tracker/wiki/Integrations-Engineer-Onboarding


Update:

1. Add snowflake query examples to check if data (transactions, ad impressions, signups) are being tracked correctly
2. How to send data to Kibana
