### ISSUE TITLE
Monitor Alerts transactions observer channel daily

### ISSUE THREAD

**Issue by pacholoamit** [MediaJel/mediajel-tracker#265]
# Description

Monitor Alerts transactions observer channel daily

**Comment by pacholoamit** [comment]
1. KanaLeaf,
- Use Image pixels

```html
< img src="https://collector.dmp.cnna.io/i?&e=tr&tr_id={{ORDERID}}&aid=Test&tr_tt={{ORDERTOTAL}}&p=web&tv=no-js-0.1.0"
```

**Comment by jonmediajel** [comment]
> ```
> <img src="https://collector.dmp.cnna.io/i?&e=tr&tr_id={{ORDERID}}&aid=Test&tr_tt={{ORDERTOTAL}}&p=web&tv=no-js-0.1.0" />
> ```

```
<script type="text/javascript">
  window.addEventListener(
    "message",
    (event) => {
      try {
        const tryParseJSONObject = val => {
          const o = JSON.parse(val);
          if (o && typeof o === "object") {
            return o;
          }
        }
        const rawData = tryParseJSONObject(event.data);
        const payload = rawData?.payload?.payload || null;
        if (rawData.event == "analytics:dataLayer" && payload.event == "purchase") {
          const transaction = payload.ecommerce;
          const { transaction_id, value } = transaction;
          var img = window.document.createElement("img")
          img.src = `https://collector.dmp.cnna.io/i?&e=tr&tr_id=${transaction_id}&aid=Test&tr_tt=${value}&p=web&tv=no-js-0.1.0`
          document.body.appendChild(img);
        }
      } catch (e) {
        throw e;
      }
    },
    false
  );
</script>
```

**Comment by pacholoamit** [comment]
window.addEventListener(
    "message",
    (event) => {
      try {
        const tryParseJSONObject = val => {
          const o = JSON.parse(val);
          if (o && typeof o === "object") {
            return o;
          }
        }
        const rawData = tryParseJSONObject(event.data);
        const payload = rawData?.payload?.payload || null;
        if (rawData.event == "analytics:dataLayer" && payload.event == "purchase") {
          const transaction = payload.ecommerce;
          const { transaction_id, value } = transaction;
        console.log("Transaction happened")
         console.log(transaction)
          var img = window.document.createElement("img")
          img.src = `https://collector.dmp.mediajel.ninja/i?&e=tr&tr_id=${transaction_id}&aid=Test&tr_tt=${value}&p=web&tv=no-js-0.1.0`
          document.body.appendChild(img);
        }
      } catch (e) {
        throw e;
      }
    },
    false
  );

**Comment by jonmediajel** [comment]
App ID: ca22a006-35f2-4d94-8745-795e1aff6487

Campaign: https://thetailoredhemp.com/

Note: 
Tested on snowflake 
They don't have frequent visitors

--------------------------------------------------------------------------

App ID: KanaLeaf

Campaign: https://www.kanaleaf.ca/

TEST: No transactions found on snowplow after successfully submitting test transaction with 2 orders - pickup

Note: Image Pixel in Javascript documentation to implement, However issue with Javascript with WIX

--------------------------------------------------------------------------

App ID: 39b77bae-da63-4b15-a463-25cc4395d113

Campaign: https://cannacea.life/

Note: 
Tested on snowflake 
They don't have frequent visitors

--------------------------------------------------------------------------

App ID: ConsiderItFlowers

Campaign: https://www.consideritflowers.com/

TEST: They have a different ID: _wn with a collector name: ec.editmysite.com

Note: We need to reinstall the pixel. 
Blocked: Credit card square transaction invalid card
Update: 24/06/2023 - GTM is reinstalled and Pixel reinstalled. We will monitor transactions

--------------------------------------------------------------------------

App ID: NutritionZone

Campaign: https://nutritionzone.shop/

Note: 
Tested on snowflake 
They don't have frequent visitors

--------------------------------------------------------------------------

App ID: Catchaphlyte

Campaign: https://catchaphlyte.com/

Note: 

Alert transaction observer showed last transaction date was  2023-06-17. 
Tested on snowflake, there was a recent transaction on 2023-06-20

**Comment by jonmediajel** [comment]
App ID: Cintron

Campaign: https://cintronworld.com/

Note:

Alert transaction observer showed last transaction date was 2023-06-20.
Tested on snowflake, there was a recent transaction on 2023-06-26

**Comment by jonmediajel** [comment]
App ID: 39b77bae-da63-4b15-a463-25cc4395d113

Campaign: https://cannacea.life/

Note:
Tested on snowflake
They don't have frequent visitors

Last Date Transaction: 2023-06-23 16:56:17.832

------------------------------------------------------------------------------------------------

App ID: ca22a006-35f2-4d94-8745-795e1aff6487

Campaign: https://thetailoredhemp.com/

Note:
Tested on snowflake
They don't have frequent visitors

Last Date Transaction: 2023-06-24 00:28:25.774

**Comment by jonmediajel** [comment]
App ID: 39b77bae-da63-4b15-a463-25cc4395d113

Campaign: https://cannacea.life/

Note:
Tested on snowflake
They don't have frequent visitors

Last Date Transaction: 2023-06-30 16:51:55.122

-----------------------------------------------------------------------------------------------------------------------------

App ID: ca22a006-35f2-4d94-8745-795e1aff6487

Campaign: https://thetailoredhemp.com/

Note:
Tested on snowflake
They don't have frequent visitors

Last Date Transaction: 2023-07-04 04:39:35.899

-----------------------------------------------------------------------------------------------------------------------------

App ID: KanaLeaf

Campaign: https://www.kanaleaf.ca/

Note:
Tested on snowflake
They don't have frequent visitors

Last Date Transaction: 2023-06-30 18:36:26.439

**Comment by pacholoamit** [comment]
Update: Notify Jon about monitoring Eaze
