### ISSUE TITLE
Make mediajel tracker support multiple app ids on the same page

### ISSUE THREAD

**Issue by pacholoamit** [MediaJel/mediajel-tracker#276]
# Description

Make the snowplow tracker name space more dynamic. Change the  `create-tracker` files on `v1` and `v2` subdirectories in the mediajel-tracker

**Comment by ZeeLiger** [comment]
created a new branch https://github.com/MediaJel/mediajel-tracker/tree/dynamic-snowplow-tracker
I have not yet created a pull request

**Comment by ZeeLiger** [comment]
Pull request can be found here: https://github.com/MediaJel/mediajel-tracker/pull/280
