### ISSUE TITLE
Review Wordpress plugin for tags

### ISSUE THREAD

**Issue by pacholoamit** [MediaJel/mediajel-tracker#279]
# Description

1. Find our wordpress plugin repo for our mediajel tracker plugin
2. Create a wordpress server locally 
3. Evaluate if the mediajel tracker plugin still works

**Comment by jonmediajel** [comment]
https://github.com/MediaJel/mediajel-wp-plugin - Created a repo for the existing wp mediajel plugin

**Comment by jonmediajel** [comment]
![Image](https://github.com/MediaJel/mediajel-tracker/assets/76018662/078601b1-7972-4b33-9032-603b1b0c047b)

tested locally having errors

**Comment by jonmediajel** [comment]
Fix on error is now done and merged - https://github.com/MediaJel/mediajel-wp-plugin/pull/1

**Comment by jonmediajel** [comment]
![Image](https://github.com/MediaJel/mediajel-tracker/assets/76018662/d19c1a25-f5a8-4900-bc68-256d82784ada)
