### ISSUE TITLE
Allow multiple tags of different configurations to be placed on the same page

### ISSUE THREAD

**Issue by pacholoamit** [MediaJel/mediajel-tracker#286]
## Description

Allow multiple tags to be placed on the same page with different configuration

Example tag 1

```html
<script src="https://tags.cnna.io/?appId=Example1&environment=dutchie-iframe"></script>
```

Example tag 2

```html
<script src="https://tags.cnna.io/?appId=Example2&environment=dutchie-subdomain"></script>
```

**Comment by jonmediajel** [comment]
As a first step for the goal I recreated multiple. Next steps to implements this dynamically in the function




![Image](https://github.com/MediaJel/mediajel-tracker/assets/76018662/2081ff51-8c7b-4773-97bc-996db9fa9362)




![Image](https://github.com/MediaJel/mediajel-tracker/assets/76018662/f69828ac-c2e3-4d3e-bbe1-b9032af63ccd)

**Comment by pacholoamit** [comment]
Update: Needs more time

**Comment by jonmediajel** [comment]
Done will demo this tomorrow

![Image](https://github.com/MediaJel/mediajel-tracker/assets/76018662/daf3eb8e-06ad-4497-987c-0618e69f6373)



![Image](https://github.com/MediaJel/mediajel-tracker/assets/76018662/e37d48f5-f157-4394-ac03-f61489234488)

**Comment by jonmediajel** [comment]
https://github.com/MediaJel/mediajel-tracker/pull/293

**Comment by pacholoamit** [comment]
Bug when testing mediajel tracker that is deployed in Staging. 

This is working very well in local setup. 


  ```
    <script src="http://localhost:3000/index.js?appId=Example2&environment=dutchie-subdomain"></script>
      <script src="http://localhost:3000/index.js?appId=Example3&environment=dutchie-subdomain"></script>
      <script src="http://localhost:3000/index.js?appId=Example1&environment=dutchie-iframe"></script> 
```

But when we try to use it duplicates the pixel

```
<script src="https://data-collector.mediajel.ninja/?appId=Example1&environment=dutchie-iframe"></script>
    <script src="https://data-collector.mediajel.ninja/?appId=Example2&environment=dutchie-subdomain"></script>
```

![Image](https://github.com/MediaJel/mediajel-tracker/assets/76018662/a2364d23-efcd-4cc2-8f03-f02175236024)



![Image](https://github.com/MediaJel/mediajel-tracker/assets/76018662/7f066386-58e0-41fc-a4ad-5b95a3a9ef35)

**Comment by kimoycatayas** [comment]
Next Steps: 
my plan is to investigate and compare the current staging branch and main branch in mediajel tracker. once we can update both staging and main, we can apply and deploy the updates and test the multiple tags in staging environment.

**Comment by pacholoamit** [comment]
Update: @jonmediajel to QA this aside from me. @ZeeLiger will QA as well

**Comment by ZeeLiger** [comment]
The local setup works fine

I found out that when you use the `https://tags.cnna.io` tracker it would work fine 

![image](https://github.com/MediaJel/mediajel-tracker/assets/129032026/bbca99f1-063c-48ba-a07e-9c1c0419912a)
![image](https://github.com/MediaJel/mediajel-tracker/assets/129032026/638b6c0b-b88d-49ae-9154-8e0ee161bf52)

But when you use the `https://data-collector.mediajel.ninja` tracker it would run X times to the number of X tags installed
An example is when i have 3 tags, then all the scripts would run 3 times so in total there would be 9 tags
As for having 2 tags, then all the scripts would run 2 times so in total there would be 4 tags

![image](https://github.com/MediaJel/mediajel-tracker/assets/129032026/ac32eafc-c8d6-4a5b-91c9-f11d1c8496a2)
![image](https://github.com/MediaJel/mediajel-tracker/assets/129032026/79112cd2-13fc-4b06-b649-c35af714c324)

**Comment by jonmediajel** [comment]
still having Duplicating Issue 

https://github.com/MediaJel/mediajel-tracker/pull/329

**Comment by pacholoamit** [comment]
Update: To take a look at this
