### ISSUE TITLE
Investigate possible Shopify duplicate transaction item values

### ISSUE THREAD

**Issue by pacholoamit** [MediaJel/mediajel-tracker#338]
# Description

We want to check if our current Shopify adapter is reporting duplicate transaction items

Reference to related existing ticket: https://github.com/MediaJel/mediajel-dashboard/issues/5223

```sql
#Fetch Order Id to see dupes
SELECT TR_ORDERID, TR_TOTAL, TR_TAX, COLLECTOR_TSTAMP FROM DATA_COLLECTION_DB.SNOWPLOW.BASE_EVENTS WHERE TR_ORDERID IN ('5742137999422 - Order #114291', '5726910218302 - Order #114019') AND APP_ID = 'f8d6e6aa-007c-42e9-89b1-5ead2105fc57'

#Fetch transactions basket items and see the to sum match the dashboard
SELECT SUM(TI_QUANTITY) AS QUANTITY, SUM(TI_QUANTITY * TI_PRICE) AS REVENUE, TI_ORDERID FROM DATA_COLLECTION_DB.SNOWPLOW.BASE_EVENTS WHERE TI_ORDERID IN ('5742137999422 - Order #114291', '5726910218302 - Order #114019') AND APP_ID = 'f8d6e6aa-007c-42e9-89b1-5ead2105fc57' GROUP BY TI_ORDERID;

#Fetch transactions basket items and see identical values
SELECT TI_NAME, TI_QUANTITY, (TI_QUANTITY * TI_PRICE) AS REVENUE, TI_ORDERID, COLLECTOR_TSTAMP FROM DATA_COLLECTION_DB.SNOWPLOW.BASE_EVENTS WHERE TI_ORDERID IN ('5742137999422 - Order #114291', '5726910218302 - Order #114019') AND APP_ID = 'f8d6e6aa-007c-42e9-89b1-5ead2105fc57'
```

**Comment by pacholoamit** [comment]
Update: Requires to setup shopify store

**Comment by ZeeLiger** [comment]
Made a Cart Searcher Based on App ID's 

Can be found in [AppID-to-Cart-Finder.ipynb](https://github.com/MediaJel/jupyter-notebooks-collection/blob/master/automations/AppID-to-Cart-Finder.ipynb)

This retrieves the App Id's that have had the `Record` Events in the last X Days (currently set to 30 days) and using the retrieved App Id's, Searches for their carts that is inside Unstruct:data:data:cart and instead returns `NoCart` if it is not found. 

This can be Converted to SQL, just some expertise is required to do so.

**Comment by ZeeLiger** [comment]
The App Id's That have the `shopify` Cart are the following: 

03d7a3fa-c4da-446e-b915-0d0c07bb9b46
52aedb57-22cb-4e72-92b6-c2cc7fe1ccdd
39b77bae-da63-4b15-a463-25cc4395d113
DiscoverCBD
6acf9c4f-394a-44e3-a094-d53937cadccb
NutritionZone
4664b890-120b-42a2-97ee-4f07ba2056cb
dabx
Cintron
hempluciduniversal
VapeCentralGroup
9f0ac3d7-ee8c-4e51-a1ad-d5b9ebccad8c
dynavap
7828ffe3-2e11-497a-9b7a-d8f3975289fb
291b8427-f382-4a64-a6b3-417eebeaa74e
35f8a88e-a59c-4c1a-8563-83e400893372
HempHop
SmokeHonest
f26aa2ad-e068-4e71-b6cb-bd845eb19c5a
4859f498-3972-4a5d-85e1-7126158d80e2
f8d6e6aa-007c-42e9-89b1-5ead2105fc57
b197a3d8-28bb-4aae-a8e7-c67795e2bd91
7f9ad02a-54b2-4416-a078-d389883bd1a2
3d862dad-4253-4052-920f-cdccfc968581

**Comment by ZeeLiger** [comment]
Here is the number of duplicate `TR_ORDERID` since `08-20-2023` by `APP_ID`


![Image](https://github.com/MediaJel/mediajel-tracker/assets/129032026/bbb64b3e-42ba-48ad-8441-afb1c4a06c19)


Here is the sum of the duplicate `TR_ORDERID` since `08-20-2023` by `APP_ID`


![Image](https://github.com/MediaJel/mediajel-tracker/assets/129032026/2d4de84b-a135-419c-8532-f715fece7763)

**Comment by ZeeLiger** [comment]
I have converted the python script into an SQL query which is for finding which App_IDs have which Carts

```
--Select recent app-id's
SELECT DISTINCT APP_ID, CART
FROM (
    SELECT DISTINCT APP_ID, date_from_parts(year(COLLECTOR_TSTAMP), month(COLLECTOR_TSTAMP), day(COLLECTOR_TSTAMP)) as DATE, EVENT_NAME, UNSTRUCT:data:data:cart as CART
    FROM DATA_COLLECTION_DB.SNOWPLOW.BASE_EVENTS
    WHERE DATE >= date_from_parts(2023,08,20) -- DATE HERE
    AND EVENT_NAME = 'record'
    ORDER BY DATE DESC
)
WHERE CART LIKE 'shopify'; -- CART HERE
```

This can now be run with just snowflake which is much faster (~6 mins) and the python notebook is no longer needed

Afterwards, This would be the script for finding the duplicate transactions 

```
--CHECK DUPLICATES
SELECT COUNT(*) as dupes_count, TR_ORDERID, APP_ID, date_from_parts(year(COLLECTOR_TSTAMP), month(COLLECTOR_TSTAMP), day(COLLECTOR_TSTAMP)) as DATE 
FROM DATA_COLLECTION_DB.SNOWPLOW.BASE_EVENTS 
WHERE APP_ID IN (
    -- APP IDS HERE
)
AND TR_ORDERID is not NULL
AND DATE >= date_from_parts(2023,08,20) -- DATE HERE
GROUP BY TR_ORDERID, DATE, APP_ID
HAVING COUNT(*) > 1;
```
