### ISSUE TITLE
investigate shopify pixels new implementation

### ISSUE THREAD

**Issue by pacholoamit** [MediaJel/mediajel-tracker#344]
# Description

Research into Shopify new pixel implementation for better recording of transactions

```html
<script src=https://tags.cnna.io/?....></script>
<script>
// pseudo-code of NEW shopify implementation
// This code will be INSIDE the universal tag in the future once testing is complete.
analytics.on("transaction", (data) => {
  console.log
})
</script>
```

**Comment by pacholoamit** [comment]
Update: Improve requirements on this ticket

**Comment by jonmediajel** [comment]
Looks like we can now get the data easily. However I haven't investigated yet the checkout page since I would be needing credit card and subscription



![Image](https://github.com/MediaJel/mediajel-tracker/assets/76018662/e03b4ca5-c7bc-47bc-9902-ba3751929b07)



![Image](https://github.com/MediaJel/mediajel-tracker/assets/76018662/7ae79e9e-65ee-4c28-89f6-311a27851a13)




Needed trial subscription



![Image](https://github.com/MediaJel/mediajel-tracker/assets/76018662/7745239d-f70e-44d2-a8ad-2b895d02cdae)

**Comment by pacholoamit** [comment]
Create credit card for Jon

**Comment by pacholoamit** [comment]
Update:
- Issued credit card to Jon for testing

**Comment by pacholoamit** [comment]
Will resolve this ticket: https://github.com/MediaJel/mediajel-tracker/issues/338

**Comment by jonmediajel** [comment]
```
var tag = window.document.createElement("script");
tag.src = "https://tags.cnna.io/?appId=JonShopify";
document.head.appendChild(tag);

analytics.subscribe("checkout_completed", (event) => {
  try {
    const products = event.data.checkout;
    const lineItems = products.lineItems;
    window.tracker(
      "addTrans",
      products.order.id,
      "N/A",
      parseFloat(products.totalPrice.amount),
      parseFloat(products.totalTax.amount) || 0,
      parseFloat(products.shippingLine.price.amount) || 0,
      "N/A",
      "N/A",
      "N/A",
      products.currencyCode || "USD"
    );
    lineItems.forEach(function (item) {
      const productItem = item.variant;

      window.tracker(
        "addItem",
        item.id,
        productItem.sku || "N/A",
        productItem.product.title || "N/A",
        "N/A",
        parseFloat(productItem.price.amount) || 0,
        parseInt(item.quantity) || 1,
        products.currencyCode || "USD"
      );
    });
    window.tracker("trackTrans");
  } catch (error) {}
});
```

**Comment by jonmediajel** [comment]
after completion of this ticket, will cancel subscription for shopify

**Comment by jonmediajel** [comment]
New Shopify API to tracker is not possible

**Comment by pacholoamit** [comment]
Update: Will re-sync up with Jon

**Comment by pacholoamit** [comment]
update:

- Change the shopify generated tag in the dashboard
- Change the documentation , specifically when the "View Instructions" button is pressed.

**Comment by jonmediajel** [comment]
Done: https://github.com/MediaJel/mediajel-dashboard/pull/5768
