### ISSUE TITLE
Add sources logging to mediajel-tracker by default

### ISSUE THREAD

**Issue by pacholoamit** [MediaJel/mediajel-tracker#346]
# Description

Log data sources by default if our tag is installed in the page. Make it look nice with a custom logger.

Implement:

- xhrSource
- dataLayerSource
- fetchSource
- etc

**Comment by pacholoamit** [comment]
Copy logger from mediajel-gql-service/src/shared/logger.ts

**Comment by SeanRizarre** [comment]
Update: 
-Merged to staging.
-Testing to see if working on live websites.

**Comment by SeanRizarre** [comment]
Update:
-Testing on a number of sites to see if problems arise for a certain sources.
-Done with making the logger look presentable.
-To be reviewed by team after testing.

**Comment by pacholoamit** [comment]
Update: To sync up with findings

**Comment by SeanRizarre** [comment]
Clients used for testing datasource:
-3ccannabisclub
-altessence
-420packaging
-cannagram
-canntinas
