### ISSUE TITLE
Research into campaign adhoc report request from Kai

### ISSUE THREAD

**Issue by pacholoamit** [MediaJel/mediajel-tracker#380]
# Description

![Image](https://github.com/MediaJel/mediajel-tracker/assets/69985528/05aa0049-23e6-4d53-8d48-1cc3c375d20c)

Check if the audience segment and deal id metrics are available from the liquid m api

**Comment by pacholoamit** [comment]
Update: Ad-hoc request is in progress

**Comment by ZeeLiger** [comment]
This is done
And the report can be generated through this PR: https://github.com/MediaJel/jupyter-notebooks-collection/blob/master/reporting/campaign-optimizations_v5-dealsegment.ipynb

**Comment by pacholoamit** [comment]
Done!
