### ISSUE TITLE
Migrate tracker from v1 to v2

### ISSUE THREAD

**Issue by pacholoamit** [MediaJel/mediajel-tracker#381]
# Description

We want to migrate from tracker v1 to v2. We need to do the following:

1. Update the `sp.js` from `v3.4.0` to `v3.22.1` , which is the latest snowplow sp.js build. Link here: https://github.com/snowplow/snowplow-javascript-tracker/releases?q=&expanded=true . 

2. Ensure that the `v2` directory tracks the same as `v1`. Test the transactions, methods, etc.

3. Modify the dashboard tag generation script to use `version=2` by default.

**Comment by jonmediajel** [comment]
In progress: https://github.com/MediaJel/mediajel-tracker/pull/383

**Comment by jonmediajel** [comment]
Done https://github.com/MediaJel/mediajel-tracker/pull/383

**Comment by pacholoamit** [comment]
https://tags.cnna.io/?appid=example&version=2

**Comment by pacholoamit** [comment]
Update: Please revert the version

**Comment by pacholoamit** [comment]
Update: Updated tracker code is on staging, merging to master next

**Comment by jonmediajel** [comment]
Tested on Tymber Cart Works well for v2



![Image](https://github.com/MediaJel/mediajel-tracker/assets/76018662/413c79cb-112a-434b-ab60-a5cf571ee7c8)
