### ISSUE TITLE
Improvements to Onboarding process

### ISSUE THREAD

**Issue by pacholoamit** [MediaJel/mediajel-tracker#387]
# Description

Make improvements to onboarding doc:
https://coda.io/d/_dKQ0zKJTphy/Tentative-Integrations-Onboarding-Document_su9g_?searchClick=b4ccf2e0-002a-42bd-b4ef-b564ff9d5013_KQ0zKJTphy

**Comment by SeanRizarre** [comment]
Updates:
* Added materials
* DAG onboarding still in progress

https://coda.io/d/DAG-Onboarding_dYIzeSESv4l/Display-Campaign-Page_sus5K#_luWTa
