### ISSUE TITLE
Create Dashboard for Tracked errors

### ISSUE THREAD

**Issue by jonmediajel** [MediaJel/mediajel-tracker#407]

**Comment by jonmediajel** [comment]
https://app.snowflake.com/rp33414/fo86278/#/tracked-errors-dFH13mG1b

**Comment by pacholoamit** [comment]
Update:

- Create a chart that shows errors by day in snowflake

**Comment by jonmediajel** [comment]
Done: 

![Image](https://github.com/MediaJel/mediajel-tracker/assets/76018662/38dcd119-b76c-467b-bf73-5b201d326f76)

**Comment by pacholoamit** [comment]
Use Apache superset for this.
