### ISSUE TITLE
Update on the MediaJel Tracker the Ecwid cart

### ISSUE THREAD

**Issue by SeanRizarre** [MediaJel/mediajel-tracker#416]
# Description
Update the Ecwid cart on the MediaJel Tracker. The location is:
src/shared/environment-data-sources/ecwid.ts

Also, take a look at v1 and v2 and update Ecwid there as well if necessary.

**Comment by SeanRizarre** [comment]
PR for QA:
https://github.com/MediaJel/mediajel-tracker/pull/417

**Comment by pacholoamit** [comment]
Update: QA
