### ISSUE TITLE
Implement Frictionless tag support feature for mediajel-tracker

### ISSUE THREAD

**Issue by pacholoamit** [MediaJel/mediajel-tracker#419]
# Description

The goal is to implement a custom domain handler in the mediajel-tracker. This will make it so, we will no longer need to request access from the client when doing custom integrations..

## Proposal 1

1. We will create a PUBLIC s3 bucket that contains javascript files
2. We will create an AWS Cloudfront distribution that points to the specific S3 bucket exposed via a specific domain endpoint (any)
3. We will write code in the mediajel-tracker that does the following: Check current domain of the tag in the page via `window.location.href` > Make a GET request to the cloudfront url + `window.location.href` . This should resolve to a javascript file specifically on the S3 bucket if it exists. If the javascript file exists for the domain, load it to the page, if it does not then do nothing.
4. We will test this on staging via creating a javascript file in the s3 bucket (I.E. buddhut.net.js), We will insert the staging tag on the target domain (I.E. buddhut.net). We should see the custom tag load

## Enhancements
- Automating and version controlling the custom domain tags via private repo and CI/CD

## Notes:
- Hash the domain names

**Comment by pacholoamit** [comment]
Update: To set up static website in S3 for testing on staging

**Comment by pacholoamit** [comment]
Updates:

1. New repo for frictionless custom tags
2. CI/CD has been created to push tags to the S3 buckets

**Comment by pacholoamit** [comment]
Think of different edge cases where issues could happen

**Comment by pacholoamit** [comment]
QA steps:

For each custom integration we need to install 2 things:

1. Production tracker = `<script src='https://tags.cnna.io/?appId=...></script>`
2. Staging tracker = `<script src='https://staging-tags.attentionsignals.net/?appId=...></script>`


Next things is we get the transaction for production and then place this on the site somehow

```js
<script>
// Get transaction somehow with javscript
window.tracker("addTrans" .... ) 

window.tracker("trackTrans") 
</script>
```


For Staging, what we need to do is add a file in the frictionless repo with the correct domain name

```ts

window.trackerStaging("addTrans" ... )


window.trackerStaging("trackTrans", ...)

```

**Comment by pacholoamit** [comment]
Sites to look at:

- https://seaweedmaine.com/
- https://www.budmary.com/
- budhut.net
- https://kushcartpdx.com/
- https://mmdshops.com/

**Comment by pacholoamit** [comment]
Updates have been made to conditionally create the staging tag

**Comment by pacholoamit** [comment]
https://github.com/MediaJel/mediajel-tracker/pull/452/files

**Comment by jonmediajel** [comment]
Added Lookah and thegreendragoncbd

https://github.com/MediaJel/mediajel-tracker/pull/454/files
