### ISSUE TITLE
Implement CI workflow for creating the S3 file for generating the carts

### ISSUE THREAD

**Issue by pacholoamit** [MediaJel/mediajel-tracker#420]
# Description

Steps:

1. @jonmediajel , we need to create a script to read the mediajel-tracker/src/v1/imports/carts/index.ts file and parse out the `environment` names into the final format of the S3 generated carts.

**Comment by jonmediajel** [comment]
For re-QA = https://github.com/MediaJel/mediajel-tracker/pull/435

**Comment by pacholoamit** [comment]
Next step: Get in touch with Devops and add the command `yarn tracker:generate-environments` in the CI process in the final step

**Comment by pacholoamit** [comment]
Implement the tracker generation script in CI

**Comment by pacholoamit** [comment]
Update: Reach out to Joseph for status on implementing script in CI

**Comment by jonmediajel** [comment]
https://github.com/MediaJel/amplication-nestjs-microservices/commit/913903535ffdbc0718e69d835da2390f7a2b2ea2
