### ISSUE TITLE
Weave cart adapter for Seed of life

### ISSUE THREAD

**Issue by pacholoamit** [MediaJel/mediajel-tracker#431]
# Description

Add Weave cart adapter to mediajel-tracker

**Comment by pacholoamit** [comment]
Update: In progress,

**Comment by SeanRizarre** [comment]
Update: To transfer and make docs for adapter that weave support made

**Comment by SeanRizarre** [comment]
https://docs.google.com/document/d/1s8DQ83FV2f4R-VJKyAt1xCFRl8uy1DeYQwjENWQWVck/edit#heading=h.ru0xovnntldt

**Comment by pacholoamit** [comment]
Steps:

Create a source called `weaveEventListener` in sources

```ts

interface WeavePayload {
event: any
}

const weaveEventListener =(callback: (data: WeavePayload) => void) => {

document.addEventListener('weave-analytics-event', event => {
        callback(event)
});

}


```

**Comment by SeanRizarre** [comment]
https://github.com/MediaJel/mediajel-tracker/pull/488
