### ISSUE TITLE
Fix 403 error when mediajel-tracker loads a non-existing frictionless tag

### ISSUE THREAD

**Issue by pacholoamit** [MediaJel/mediajel-tracker#466]
# Description

When the mediajel-tracker tries to load a non-existing frictionless tag. We get an error log like below:

```
 GET https://d2tw82ik2m9s0b.cloudfront.net/domains/d3d3LmxpdmV3aXRoc29sLmNvbQ==.js 403 (Forbidden)
```

![Image](https://github.com/user-attachments/assets/f1d5a838-b9a1-416f-81e8-299b629546c0)

This happens consistently for sites that do not have a frictionless tag.

Example site: https://www.livewithsol.com/

## Definition of Done

- For sites, where there are no frictionless tags installed on them... This error should not log in the console.

**Comment by jlaridamediajel** [comment]
Resolutions
Need to setup cloudfront error handling (400,403,404) for the custom tag. returning any 400+ errors as an empty .js



![Image](https://github.com/user-attachments/assets/182cbb27-fd2a-446c-add6-65dc38db1ca2)


Localhost


![Image](https://github.com/user-attachments/assets/53d56cdf-badb-4369-92aa-95b09c778247)

**Comment by jlaridamediajel** [comment]
resolve sample issue


![Image](https://github.com/user-attachments/assets/bc12c016-149b-4010-9d7e-f9ca7364d832)


Previous Custom tag site is still working



![Image](https://github.com/user-attachments/assets/e03c6c63-0e40-455a-8f52-2430e4d56c1f)



![Image](https://github.com/user-attachments/assets/8d8bf6f5-3aea-4d4f-aecc-22ba61d241f0)
