### ISSUE TITLE
Sign up schema changes

### ISSUE THREAD

**Issue by pacholoamit** [MediaJel/mediajel-tracker#468]
# Description

Make changes to the `sign-up` schema in [here](https://github.com/MediaJel/mj-snowplow-management/blob/master/iglu/schemas/com.mediajel.events/sign_up/jsonschema/1-0-3)

# Definition of Done
- Add a property "metadata" that is a dynamic object
- Add a property "type" that accepts a string
- Test out the new sign_up schema by sending a new event and checking snowflake/clickhouse if the new "metadata" and "type" properties are populated

**Comment by pacholoamit** [comment]
Check in snowflake


````
SELECT * FROM DATA_COLLECTION_DB.SNOWPLOW_INGEST.BASE_EVENTS
WHERE EVENT_NAME = 'sign_up'
```

Check the `UNSTRUCT` column, this will contain the additional properties from the sign up event

**Comment by jlaridamediajel** [comment]
![Image](https://github.com/user-attachments/assets/e757f788-0374-4469-bd8a-b1d750a3e4e1)

Seen the changes on snowflake

**Comment by pacholoamit** [comment]
Check the following tables:

- BASE_EVENTS_3_MONTHS
- BASE_EVENTS_6_MONTHS
- BASE_EVENTS_1_YEAR
