### ISSUE TITLE
Create Wix ecommerce cart adapter

### ISSUE THREAD

**Issue by pacholoamit** [MediaJel/mediajel-tracker#473]
# Description

I cannot believe it took us this long to find this...

https://support.wix.com/en/article/tracking-google-ads-conversions-using-wix-custom-code

## Todos:

- Add Wix Ecommerce Adapter in mediajel-tracker, branch off from staging
- implement the wix-ecommerce adapter tag on a client: https://www.hypnoticherb.com/ , Ask them to change the tag
- update microservices for carts  (use jon's auto-update script)

**Comment by jonmediajel** [comment]
https://github.com/MediaJel/mediajel-tracker/pull/477

**Comment by jonmediajel** [comment]
Working well!



![Image](https://github.com/user-attachments/assets/14a64b26-dbf9-4342-af4c-49a8cd816529)

**Comment by jonmediajel** [comment]
Auto generated - https://mjcarts.s3.amazonaws.com/environments.js
