### ISSUE TITLE
Misconfigured tag issue - LowKeyDispensary

### ISSUE THREAD

**Issue by pacholoamit** [MediaJel/mediajel-tracker#487]
# Description

https://mediajel.slack.com/archives/D01HNNHQ9JA/p1723253938952399

![Image](https://github.com/user-attachments/assets/6112d58f-6cd0-470d-9ca2-66492b29c6b7)

**Comment by jonmediajel** [comment]
https://coda.io/d/_dsKW6gcriTa#Integrations-Requests-Board_tuSsT/r257&view=modal

**Comment by pacholoamit** [comment]
Updates: Coordinated with the TAM team

**Comment by pacholoamit** [comment]
Update: Change Query to accommodate the sum of the device ids per person
