### ISSUE TITLE
Sweed Cart Adapter

### ISSUE THREAD

**Issue by jonmediajel** [MediaJel/mediajel-tracker#493]
All new Sweed Cart

Tested the same code for both with the same cart named sweed

https://shop.californiaholistics.com/
https://shop.oxnardholistics.com/

**Comment by jonmediajel** [comment]
https://github.com/MediaJel/mediajel-tracker/pull/492

**Comment by pacholoamit** [comment]
Awesome! Great work!

Next steps: Update microservice

**Comment by jonmediajel** [comment]
Done: https://github.com/MediaJel/amplication-nestjs-microservices/pull/530
