### ISSUE TITLE
Onboarding mediajel.com to dashboard (SEO)

### ISSUE THREAD

**Issue by pacholoamit** [MediaJel/mediajel-tracker#497]
# Description

We have a new site: mediajel.com 

The goal is to do the following:

- [x] - Verify and/or setup Google Search console for mediajel.com
- [x] - Verify and/or setup Google Analytics (GA4) for mediajel.com, ensure that you can access the GA4 view
- [x] - Onboard mediajel.com in the dashboard SEO feature, follow the Coda doc guide

**Comment by SeanRizarre** [comment]
Updates: 
- Done, followed this doc: https://coda.io/d/Engineering_dKQ0zKJTphy/Google-Search-Console-integrations_suqo1vpE#_luZtsH5H
