### ISSUE TITLE
Investigate the cause of the issues in the Transaction Values Monitoring Dashboard

### ISSUE THREAD

**Issue by SeanRizarre** [MediaJel/mediajel-tracker#501]
## Objective
1. Check and see all the AppIds in the monitoring dashboard.
2. Investigate the sites for the AppIds to see if the cause of this is a tracker version issue.
    - For more info regarding the version issue, read the docs located below the page of the link here. (https://coda.io/d/Integrations-Requests_dsKW6gcriTa/Integrations-Manifesto_suf6p_La?utm_source=slack&utm_content=comment_notification#_lup_JOlZ)

Monitoring Dashboard: https://app.snowflake.com/rp33414/fo86278/#/transaction-values-monitoring-dba0tvk60

**Comment by SeanRizarre** [comment]
## In frictionless repo
1. highroller - https://www.hrdelivery.co/



## Not in frictionless repo

**Comment by jlaridamediajel** [comment]
[version-issue-list.csv](https://github.com/user-attachments/files/16936299/version-issue-list.csv)
Sites with  issues on snowflake

**Comment by jlaridamediajel** [comment]
List of sites with tag issues on snowflake

[version-issue-list.csv](https://github.com/user-attachments/files/16936455/version-issue-list.csv)

**Comment by SeanRizarre** [comment]
| APPID                                 | DOMAINCLIENT             | LATEST_DATE | FIRST_DATE_ISSUE | FAILURE_COUNT_TOTAL |
|---------------------------------------|--------------------------|-------------|------------------|---------------------|
| 30b01512-0bc4-4957-bbb8-cf388ac493b4  | DOMAINCLIENT             | 09/09/2024  | 10/08/2024       | 15804               |
| highroller                            | hrdelivery.co.            | 09/09/2024  | 10/08/2024       | 15801               |
| 81eb5e68-cbac-4e87-9c96-a03f6d4e1b49  | viiahemp.com              | 09/09/2024  | 10/08/2024       | 11155               |
| 287ceffb-8e2e-4d6c-a2f0-933ddbeee039  | dynavap.com               | 09/09/2024  | 10/08/2024       | 2342                |
| 9112b564-7b39-4673-908e-b7879c7f05a0  | claritycannabis.us        | 21/08/2024  | 10/08/2024       | 1364                |
| 4ad367bb-f008-4681-9fd9-c7709018fd80  | claritycannabis.us        | 07/09/2024  | 10/08/2024       | 1360                |
| 6dc16783-5dfc-4a4c-ad54-bd61623a40c6  | botanyfarms.com           | 09/09/2024  | 20/08/2024       | 1254                |
| c8a5ce4c-4e76-49d7-a585-6f897d8fbe1b  | nothingbuthemp.net        | 09/09/2024  | 10/08/2024       | 988                 |
| 06c2e336-6086-4fae-bd3e-19bd9a6470cb  | thehempcollect.com        | 30/08/2024  | 10/08/2024       | 653                 |
| 092e547f-72c8-4810-85fe-596131ac2421  | weedgets.com              | 09/09/2024  | 10/08/2024       | 645                 |
| 79cdd280-6c4d-4ca6-88ad 228592798ee4  | lowkeydispensary.com      | 09/09/2024  | 04/09/2024       | 480                 |
| 6960f6c5-ea2b-4860-9aa7-ce19e0b0993a  | diamondcbd.com            | 14/08/2024  | 12/08/2024       | 257                 |
| fec233b7-71a8-4ccf-93ac-d092c2964613  | abstraxtech.com           | 09/09/2024  | 29/08/2024       | 132                 |
| 7bc01df0-c859-4392-b90d-a949e95dfe6f  | seedoflifelabs.com        | 17/08/2024  | 10/08/2024       | 70                  |
| 39115c1f-6a33-42d5-adc2-b5d96cd17707  | thickassglass.com         | 09/09/2024  | 10/08/2024       | 51                  |
| 50a31868-2007-4e22-8b25-d2310510a9ad  | looperverse.com           | 13/08/2024  | 12/08/2024       | 18                  |
| a154051f-00b0-4c69-8c68-43a295e47722  | experiencecbd.com         | 03/09/2024  | 14/08/2024       | 7                   |
| 3b8a9cb9-3b6c-4d07-a0dd-146723d370fb  | ochoextracts.com          | 06/09/2024  | 13/08/2024       | 6                   |
| 4664b890-120b-42a2-97ee-4f07ba2056cb  | dynavap.com               | 02/09/2024  | 26/08/2024       | 3                   |
| 4aeddfc4-04d9-4a94-8cd6-0bc1944b27f3  | southernease.com          | 18/08/2024  | 10/08/2024       | 2                   |
| HelloWorld                            | claritycannabis.us        | 04/09/2024  | 04/09/2024       | 1                   |
| 7b86845d-35a8-4749-9107-60b12522cf8b  | leafly.com                | 20/08/2024  | 20/08/2024       | 1                   |
| jontestprodshopify                    | 6348c6-3a.myshopify.com   | 07/09/2024  | 07/09/2024       | 1                   |


Completed:
1. 79cdd280-6c4d-4ca6-88ad 228592798ee4

**Comment by jlaridamediajel** [comment]
UPDATE

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/User/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/User/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


APPID | DOMAINCLIENT | LATEST_DATE | FIRST_DATE_ISSUE | FAILURE_COUNT_TOTAL | FRICTIONLESS | STATUS
-- | -- | -- | -- | -- | -- | --
30b01512-0bc4-4957-bbb8-cf388ac493b4 | hrdelivery.co. | 9/9/2024 | 8/10/2024 | 15810 | no | FAILED
highroller | hrdelivery.co. | 9/9/2024 | 8/10/2024 | 15806 | no | FAILED
81eb5e68-cbac-4e87-9c96-a03f6d4e1b49 | viiahemp.com | 9/9/2024 | 8/10/2024 | 11176 | no | FAILED
287ceffb-8e2e-4d6c-a2f0-933ddbeee039 | dynavap.com | 9/9/2024 | 8/10/2024 | 2342 | no | FAILED
6dc16783-5dfc-4a4c-ad54-bd61623a40c6 | botanyfarms.com | 9/9/2024 | 8/20/2024 | 1264 | no | FAILED
c8a5ce4c-4e76-49d7-a585-6f897d8fbe1b | nothingbuthemp.net | 9/9/2024 | 8/10/2024 | 989 | no | FAILED
092e547f-72c8-4810-85fe-596131ac2421 | weedgets.com | 9/9/2024 | 8/10/2024 | 643 | no | FAILED
79cdd280-6c4d-4ca6-88ad 228592798ee4 | lowkeydispensary.com | 9/9/2024 | 9/4/2024 | 480 |   | PASS
fec233b7-71a8-4ccf-93ac-d092c2964613 | abstraxtech.com | 9/9/2024 | 8/29/2024 | 136 |   | FAILED
39115c1f-6a33-42d5-adc2-b5d96cd17707 | thickassglass.com | 9/9/2024 | 8/10/2024 | 51 |   | PASS



</body>

</html>

**Comment by SeanRizarre** [comment]
Updates:
- Already in progress and still waiting on media ops.
