### ISSUE TITLE
Sweed Cart Display Tracking

### ISSUE THREAD

**Issue by jonmediajel** [MediaJel/mediajel-tracker#529]
Sweed Display tracking. Used to be working well. However its now inconsistently working. Sometimes its tracks display. Sometimes its not

**Comment by jonmediajel** [comment]
Upon Several test and debugging it seems there is something wrong with sweed + with googleAds plugin

Tested Custom Sweed Code tag  - **WORKS WELL**
Tested Sweed Cart Tag without googleAds plugin - **WORKS WELL**
Tested Sweed Cart Tag with googleAds plugin - **Sometimes it works and sometimes it doesn't. Also Add / remove to cart function seems to duplicate incrementally** - Will investigate further.

**Comment by SeanRizarre** [comment]
Pach is currently taking a look. Connected to google ads plugin issue.

**Comment by jonmediajel** [comment]
Thanks for the greatwork @pacholoamit - https://github.com/MediaJel/mediajel-tracker/pull/548

**Comment by pacholoamit** [comment]
Open until mediajel-tracker pushed to production

**Comment by pacholoamit** [comment]
Update: @jonmediajel will do testing on the sites with issues

**Comment by jonmediajel** [comment]
![Image](https://github.com/user-attachments/assets/90f290e3-0817-4e6c-bd08-4f17218b2a9b)

![Image](https://github.com/user-attachments/assets/bd838d21-9321-450f-a279-17dde6bb3423)

![Image](https://github.com/user-attachments/assets/f1739d7e-78df-4ae0-aaa6-4a61f1a2d708)

QA Results: 

Display and Google ads are working well
